print("Enter the coordinates of point a")
x1=int(input("Enter the value of x1 = "))
y1=int(input("Enter the value of y1 = "))
print("Enter the coordinates of point b")
x2=int(input("Enter the value of x2 = "))
y2=int(input("Enter the value of y2 = "))
slope=(y2-y1)/(x2-x1)
print("The slope of line is: ",slope)