print("<<< Hey Programmers !!! Welcome to python programming >>>")
print("<<< This python program is for calculating Volume of Cone >>>")
print("------------------------------------------------------")
r=float(input("Enter the value of radius: "))
h=float(input("Enter the value of height: "))
pie=float(input("Enter the value of pie: "))
Vol=pie*r*r*h/3
print("------------------------------------------------------")
print("The volume of cone= ", Vol)
print("\n<<< Thank You for using my Program !!! >>>")